### ISSUE TITLE
A slight error in your code .

### ISSUE THREAD

**Issue by MohitChattlani** [sardananishant/stone-paper-scisor-python#2]
According to your code, there was a slight error given in the picture below . I have submitted a pull request regarding its correction . Please check it and tell me if it persists . 
![error](https://cloud.githubusercontent.com/assets/19841485/22019078/eadf076e-dcd7-11e6-8591-fb96ea84e5a1.PNG)

**Comment by nishants906** [comment]
ya its correct, but i have already point out this mistake before . its just the mistake in my condition, if you look at the previous commit you will get to know that in place of scisor ..i wrote paper in condition.thats why this error was there
